### PR TITLE
Group time limits in config.yml

### PR DESCRIPTION
**Pull request by hugo213**
Allows problem authors to set time limits for *groups* in `config.yml`. Time limits for groups can be overriden by time limits for single tests.

### CODE REVIEW

**Comment by michcioperz** [comment]
Weird, I swear I saw a closed ticket on JIRA for adding this feature before.

**Comment by michcioperz** [comment]
Ah, never mind. I see now what you did there, a shorthand syntax for assigning a time limit to a whole group rather than each test separately.

**Comment by hugo213** [comment]
We have this little feature in Staszic and yesterday I heard that people want it on OI too

**Comment by michcioperz** [comment]
I think the regex is ugly yet I can't think of a cleaner way to get the group number.
I think it would be good to write a simple test (could be just another variation of Sumżyce tgz package) to verify that it works.

**Comment by hugo213** [comment]
There was indeed a cleaner way. Group number is stored in `group` variable which I was unaware of.

**Comment by accek** [comment]
That's a nice improvement, thanks!

I think this one deserves a test, though. Existing mechanism was tested indirectly here:
https://github.com/sio2project/oioioi/blob/master/oioioi/sinolpack/tests.py#L291
but it may be easier to make a new one similar to this:
https://github.com/sio2project/oioioi/blob/master/oioioi/sinolpack/tests.py#L155
rather than changing the first one. What do you think?

**Comment by hugo213** [comment]
To write any bigger piece of code I'd have to set up a dev server with your version of sio2. When I find enough free time to do so, I will submit the tests. I'm sorry, but because of many other responsibilites it might take me some time.

**Comment by accek** [comment]
No hurry. :-)

If you just want to run tests, then setting up virtualenv and using the bundled requirements.txt should be enough.

**Comment by michcioperz** [comment]
I think this might be a subset of https://github.com/sio2project/oioioi/commit/af30a2b4a551987803a92acecbbcc172c4d7ae66

**Comment by DietPawel** [comment]
As this thread had no activity for past 2 years and similar improvements were implemented I am closing the pull request.
But fell free to reopen if the functionality is not there.

**Pull request closed without merging**
